/* Device fixtures generated by tools/fixtures-from-pydevccu.js: one file per
   device type with device/channel descriptions and VALUES paramset
   descriptions. `load(type)` returns the raw fixture, `ccuFor(type)` a
   FakeCcu populated with it. */

const fs = require('node:fs');
const path = require('node:path');
const {FakeCcu} = require('./fake-ccu');

const dir = path.join(__dirname, '..', 'fixtures', 'devices');

let index;

/** fixture file for a type, case-insensitive (pydevccu spells some types in upper case) */
function fileName(type) {
    if (!index) {
        index = new Map(fs.readdirSync(dir).map((f) => [f.toLowerCase(), f]));
    }

    const wanted = (type.replace(/[^\w.-]/g, '_') + '.json').toLowerCase();
    const found = index.get(wanted);
    if (!found) {
        throw new Error('no fixture for device type ' + type);
    }

    return found;
}

function types() {
    return fs
        .readdirSync(dir)
        .filter((f) => f.endsWith('.json'))
        .map((f) => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')).device[0].TYPE)
        .sort();
}

function load(type) {
    return JSON.parse(fs.readFileSync(path.join(dir, fileName(type)), 'utf8'));
}

/** interface a fixture belongs to, from its address/type shape */
function ifaceOf(fixture) {
    const type = fixture.device[0].TYPE;
    if (/^HmIPW?-/i.test(type) || /^ELV-SH-/i.test(type) || /^ALPHA-IP/i.test(type)) {
        return 'HmIP-RF';
    }

    if (/^HMW-|^HBW-/i.test(type)) {
        return 'BidCos-Wired';
    }

    return 'BidCos-RF';
}

/**
 * FakeCcu with the fixture's device loaded (address = the fixture's own),
 * channel names "<TYPE> <index>" unless given, values empty unless given.
 */
function ccuFor(type, {channelNames, values, iface} = {}) {
    const fixture = load(type);
    iface = iface || ifaceOf(fixture);
    const devices = {};
    const names = {};
    for (const d of fixture.device) {
        devices[d.ADDRESS] = d;
        names[d.ADDRESS] = d.PARENT ? `${fixture.device[0].TYPE} ${d.INDEX}` : fixture.device[0].TYPE;
    }

    const ccu = new FakeCcu({
        iface,
        devices,
        channelNames: {...names, ...channelNames},
        values: values || {},
        paramsets: fixture.values,
    });
    ccu.fixture = fixture;
    ccu.device = fixture.device[0];
    ccu.address = fixture.device[0].ADDRESS;
    return ccu;
}

module.exports = {types, load, ccuFor, ifaceOf};
